package main

import(
	"fmt"
	"os"
	"encoding/json"
	"io/ioutil"
	"github.com/socifi/go-logging-facility/handlers/init"
)

type AutoGenerated struct {
	/* Your config here... */
	Logging loginit.LogConfig `json:"logging"`
}

func main() {
	raw, err := ioutil.ReadFile("./config.json")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}

	var c AutoGenerated
	json.Unmarshal(raw, &c)
	fmt.Printf("%#v\n", c)
	loginit.Init(c.Logging)
}
